name: image_grid_viewer_test
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  chopper: ^7.0.8
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  chopper_generator: ^7.0.5
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  freezed: ^2.4.6

flutter:

  uses-material-design: true

